export const T = {
    bg: "var(--bg)",
    surface: "var(--surface)",
    surfaceHover: "var(--surfaceHover)",
    surfaceBorder: "var(--surfaceBorder)",
    text: "var(--text)",
    textSec: "var(--textSec)",
    textTer: "var(--textTer)",
    white: "var(--white)",
    accent: "var(--accent)",
    accentText: "var(--accentText)",
    ghost: "var(--ghost)",
    bgNav: "var(--bgNav)",
    font: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
    rSm: 10, rMd: 20, rLg: 30, rFull: 9999, rImg: 8,
    mention: "var(--mention)",
};
